### ISSUE TITLE
(Ne)funkční Vodafonepark brána a nefunkční Vodafone brána

### ISSUE THREAD

**Issue by Xtek** [kparal/esmska#499]
Zdravim, 

nevim zda-li tyto problemy nebyly reseny nize (pred 5ti dny), ale dle vseho se jedna o nove issue, jelikoz jeste vcera mi brana Vodafonepark normalne fungovala. Od dnesni noci jsem zaznamenal nestandartni chovani: po odeslani SMS mi naskocilo podivne hybridni okno podobne tomu, kdyz nelze SMS odeslat z duvodu nejake chyby. Nicmene pod hlavickou tohoto okna ("chyby") byl text, ze SMS byla uspesne odeslana a vyzva k ulozeni neznameho cisla.. (?). Esmeska se zastavila a SMS je zprava je ve fronte, tudiz neni ani tato pseudoodeslana SMS logicky v HIstorii.
Nicmene, na mou takto odeslanou SMS mi prisa rano odpoved, takze mam potvrzeno, ze dosla! 

Vodafone branu jsem zkousel az nyni a tam naskocila hlaska "Doslo k nezname chybe. Brana ma zrejme aktualne problemy". 

muzete mi poradit jak vec dat do puvodniho stavu? 

verze: 1.9
OS: WXP
Java: 8.45

**Comment by kparal** [comment]
Budu moct vyzkoušet večer nebo přes víkend, tak uvidíme.

**Comment by kparal** [comment]
Je to tak, je to rozbitý. Zkusím se na to podívat.

**Comment by kparal** [comment]
Snad spraveno v 3b2fc318.

**Comment by Xtek** [comment]
Potvrzuji,vse s Vodafonepark funguje, coz je primarni. Nicmene stale mi nejde odeslat SMS skrze branu Vodafone - pokud zadam "Podpis: zadny", tak to take nejde odeslat s hlaskou, ze "tato brana vyzaduje vyplneny podpis uzivatele". Pokud vyplnim me cislo plus jmeno nebo jen cislo a jmeno, tak to presto nejde odeslat. 

jak tedy s branou Vodafone, prosim? 

kazdopadne dekuji za opravu Vodafonepark!;)

**Comment by kparal** [comment]
U Vodafone brány je nutné vyplnit číslo, jméno není nutné. Zkus restartnout esmsku a poslat čistou novou zprávu (ne z fronty). Pokud to stále nefunguje (mě ano), tak přilož console.log [1].

[1] https://github.com/kparal/esmska/wiki/FAQ#where-is-the-program-log-stored
