### ISSUE TITLE
Nefunkční T-Mobile SMS brány (T-Zones, T-Mobile) 

### ISSUE THREAD

**Issue by Subtec** [kparal/esmska#500]
Dobry den, 

k dnesnimu dni jsem zaznamenal nefunkcni SMS brany T-Mobile a to konkr.: T-Zones (free) a T-Mobile. Veri Esmsky mam 1.9. Zkousel jsem se prihlasit k branam pres webove rozhrani spol. T-Mobile a tam se zda vse funguje. 

Zaznamenal jsem, ze T-Mobile zmenil cestu ke sluzbe. Nyni je SMS brana na: https://www.t-mobile.cz/sms/open.jsp (drive byla na https://sms.client.tmo.cz/closed.jsp). 

Muzete se prosim na to kouknout a opravit to?;) 

Diky 
S.

**Comment by kparal** [comment]
Bohužel na to nemám čas. Skripty bran se dají lehce upravovat, zkus to opravit a až to začne fungovat, tak mi sem pošli spravenou verzi brány.

**Comment by frantamiz** [comment]
Dobrý den, pokusil jsem se opravit bránu T-Mobile (nyní mi funguje). Dá se ten soubor nahrát přímo sem nebo to musím udělat přes pull request? Zatím mi to nejde nahrát. Díky za radu.
Franta Mizera

**Comment by kparal** [comment]
Obávám se, že github nahrávání libovolných souborů do issues nepodporuje. Pull request je ideální. Pokud ti to nepůjde, tak přímo sem do textu vlož diff.

**Comment by peci1** [comment]
Pull request lze vytvorit z prohlizece bez nutnosti klonovat repozitar:
Jdi na https://github.com/kparal/esmska/blob/master/gateways/%5BCZ%5Dt-zones.gateway
Vpravo nahore je ikona tuzky, po kliknuti na ni se prepnes do "edit" modu, a po "ulozeni" se pull request vytvori automaticky.

**Comment by frantamiz** [comment]
Díky moc.
Franta

**Comment by kparal** [comment]
Dejte vědět, jestli t-mobile teď funguje. t-zones je hádám pořád rozbitý.

**Comment by filippekarek** [comment]
Zdravim, upravil jsem t-zones branu. Funuguje mi. Je  Chtěl jsem se ještě zeptat. Metoda send() se vždy přihlásí a na konci odhlásí, jak by se dalo udělat odhlášení až po odeslání celé dávky zpráv?

**Comment by Subtec** [comment]
Dobry den, potvrzuji, ze po updatu brana T-Mobile funguje. Brany T-Zones a T-Zones(free) vsak nikoli. Verim, ze se to nejak podari.

**Comment by kparal** [comment]
Updatnul jsem teď i tu t-zones free. Na t-zones čekám v #502.

**Comment by kparal** [comment]
Mělo by to být vyřešeno. Kdyby ne, přijímám další patche.
