### ISSUE TITLE
Nefunkční SMS brána O2[CZ]  (4.11.2015)

### ISSUE THREAD

**Issue by Subtec** [kparal/esmska#509]
Zdravim, 

zaznamenal jsem jiz pred par dny nefunkcni SMS branu "O2 CZ (registrace)". SMS nelze zaslat, objevi se chybova hlaska sdelujici, ze ma brana pravdepodobne nejake problemy. Mam overeno, ze problem je opravdu v Esmesce, jelikoz zasilani pres Oskarka funguje. Z toho dedukuji, ze je problem prave v Esmesce. 

Prosim o vyreseni problemu;) 

Dekuji
S.

**Comment by kparal** [comment]
OK, nemám čas to řešit, ale přijímám patche.

**Comment by frantamiz** [comment]
Zdravím, zjistil jsem, že problém je ve funkci logout(). Bohužel to nemám jak testovat.....(Nemám O2). Zkusil jsem zakomentovat 
//EXEC.getURL("http://sms.1188.cz/logout", []) v této funkci
a fungovalo mi to.

**Comment by peci1** [comment]
A smsky to teda posila nebo ne? :)

**Comment by kparal** [comment]
No, já myslím že cookies stejně mezi jednotlivými zprávami nepředávám, takže ten logout asi není potřeba. Vyzkoušejte poslat bez odhlášení několik zpráv za sebou, pokud to bude fungovat, tak by ta funkce neměla být potřeba.

**Comment by frantamiz** [comment]
Teď jsem to otestoval jednou sms a normálně přišla. Stačí tedy odstranit funkci logout(). Je ale potřeba otestovat více sms za sebou, jak psal pan Páral... To musí asi někdo, kdo má O2.

**Comment by kparal** [comment]
Začleněno jako f9bf615910e. Snad to pomůže.
