### ISSUE TITLE
getMaxChars cant be more then 1000

### ISSUE THREAD

**Issue by tomaskovacik** [kparal/esmska#510]
hi,

I just want to test something  and cant type message while [INT]Gosms gateway is selected, status bar say "Text to long!" 
![esmska](https://cloud.githubusercontent.com/assets/4346464/10970880/90ebb19a-83d1-11e5-8e8d-1c4377f1b967.png)

problem is on gateway definition:

function getMaxChars() {
    return 1404
}
or in maxMessageLength = 1000 in Gateway.java, it depends on on way you look at it :)

anyway changing gateway definition to 

function getMaxChars() {
    return 1000
}
fix the problem

but as gateway realy has support 1404 chars in single request, it will be better to change maxMessageLength to 1404

I dont think you need patch for this, but if so, tell me what you want to do, i made patch/pull request  whatever

t.

**Comment by peci1** [comment]
Can't it be related to https://github.com/kparal/esmska/issues/470 ?

**Comment by tomaskovacik** [comment]
what ever :dancer: 
having some hard limit somewhere in code and then read other number from config file and do not check whatever is that number usable in next calculation (1000/1404 must be at least 1) and then don't allow user to send sms is bug 

in my opinion: value from *.gateway should be tested and if its greater then 1000 we should change maxMessageLength.

i do not go to debate whatever is hard limit maxMessageLength good/bad I understand why it is there, and also disagree that is somehow useful  ..... this is about not functional gateway, so I just want to now how author of esmska want to have fixed this.

Me as author of gateway want to have it fully functional so 1404 chars per one request

t.

**Comment by peci1** [comment]
Then let's try to fix it in a Pull Request. @kparal no longer has time for bugfixes.

**Comment by kparal** [comment]
3325731c34 should fix it. I could publish a new esmska release, even though something tells me not that many people use this gateway... the problem has probably existed for years. Is it important for you?
The message length is now hard capped at 1000 chars (even if the gateway defines a higher value).

**Comment by tomaskovacik** [comment]
isn't update of gateway automaticly downloaded by clients? if so, fix of gateway is ok. I do not use it, so it's just to have it fixed.

**Comment by kparal** [comment]
I fixed it in program itself, not gateway. But it's true that we can simply change the max limit from 1404 to 1000 and the problem is fixed even with a gateway update. Will do that.
