### ISSUE TITLE
Opensuse release repo: key expired

### ISSUE THREAD

**Issue by peci1** [kparal/esmska#513]
The repo key on opensuse.org got expired. Can we ask you, Kamil, to create a new one?

**Comment by kparal** [comment]
Sure. I'll try to figure out how to do that. (If somebody knows, I'm all ears). I'll probably try force-rebuild first, maybe that could fix it.

**Comment by peci1** [comment]
Sorry, I can't help with this, as I also haven't ever done it.

**Comment by kparal** [comment]
What about now, does it work?

**Comment by peci1** [comment]
Yes, it seems so. Thanks!

It was only needed to do

     wget -O - 
http://download.opensuse.org/repositories/Java:esmska/common-deb/Release.key 
| sudo apt-key add -

, which is the standard thing you do when a repo key expires.
-- 
Martin Pecka

**Comment by kparal** [comment]
Hmm, it would be nicer to have the key redownloaded automatically. But I don't really know if it is possible. So at least this way. Thanks for your report.

**Comment by peci1** [comment]
I think (but it's not based on proofs) that the problem is the key wasn't exchanged before it expired. It'd also look strange for me if users would be forced to do this every 3 years for each of their custom APT repositories.
