### ISSUE TITLE
Vodafone park zrusen.

### ISSUE THREAD

**Issue by peci1** [kparal/esmska#515]
Kamile, Vodafone park byl zrusen bez nahrady. Bylo by tedy dobre odstranit ho ze seznamu bran. Misto nej se da pro SMS do Vodafone pouzit gosmsgo.cz, coz by mohla byt i brana doporucena pro pouziti misto VF parku.

Pokud nechcete zmene venovat cas, muzu to otestovat u sebe a poslat PR bez Vodafone; jen si chci overit, ze prijmete i PR, ktery branu neupdatuje, ale rusi.

**Comment by kparal** [comment]
Ahoj, pošli PR, díky. Smazání brány se ale u uživatelů neprojeví dokud nevydám novou verzi programu (a oni si ji nenainstalují), což nevím, zda stojí za tu práci.

**Comment by peci1** [comment]
A co takhle? https://github.com/kparal/esmska/pull/516

**Comment by kparal** [comment]
To by mělo fungovat. Díky.
