### ISSUE TITLE
Nefunkční SMS brány T-Zones & T-Zones[free] (22. 11. 2017) 

### ISSUE THREAD

**Issue by valouchmarek** [kparal/esmska#520]
Pěkný den,

chtěl bych nahlásit nefunkčnost obou bran pro T-mobile. Na webu posílání funguje.

**Comment by kparal** [comment]
Viz úvodní stránka. Pokud to někdo opraví, tak to vydám, ale sám to již nespravuji.

**Comment by Subtec** [comment]
Dovolil bych se primluvit za to, aby se "nekdo" obetoval a zaplatu vydal. Byla by velka skoda, kdyby tento jinak vynikajici program skoncil.

**Comment by mpavlase** [comment]
Žádný problém s bránami T-Mobile ani t-zones se u mě nekoná... zkuste poslat debug výpis:
`esmska --debug network 2> esmska.log`

**Comment by iki** [comment]
@mpavlase mam od vcera take problem s t-zones (login) ... pouzivam esmsku-portable na win a parametr --debug network  nema vliv (debug log request/response na strderr neni)

**Comment by peci1** [comment]
Nevim, jestli to je VF nebo TM, ale obcas delaji to, ze nekterym (nahodnym?) lidem zobrazujou trochu jinou stranku...

**Comment by mahdi1234** [comment]
Mam to posledni dva dny taky repor jak win tak linux ...

```
Nov 24, 2017 10:45:35 AM esmska.transfer.GatewayExecutor getURL
WARNING: Could not execute getURL
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

```
[esmska.txt](https://github.com/kparal/esmska/files/1501202/esmska.txt)

**Comment by kryshtof** [comment]
problém je (nejspíše) jen  v portable verzi, když spustím přímo esmska.jar (tedy s použitím javy nainstalované v systému) tak to funguje.

**Comment by kparal** [comment]
Je možné, že přibalená verze Javy nezná certifikační autoritu, kterou začal T-mobile používat. Nebo možná nějaký nový hashovací algoritmus, atp. Je z konce roku 2011.

**Comment by mahdi1234** [comment]
dik, java -jar ./esmska.jar funguje, takze to bude to cert autoritou zrejme.

**Comment by kparal** [comment]
Zkuste někdo tuto verzi, přibalil jsem tam novější Javu:
http://ripper.profitux.cz/esmska/beta/Esmska-1.9.1-portable.7z
Je tam Java 8 místo Javy 6, takže se něco mohlo rozbít.

**Comment by ghmv** [comment]
Kamile, tvoje nová verze 1.9.1 opravdu na windowsech zase funguje (na linuxech problém nebyl). Dík!
(Uděláš prosím nový instalátor?)

**Comment by kparal** [comment]
Přidal jsem 1.9.1 do odkazů ke stažení. Dejte vědět jestli to pomohlo.

**Comment by Subtec** [comment]
Potvrzuji, ze nova Portable verze 1.9.1 funguje (W7 32bit). 
Diky!

**Comment by kparal** [comment]
Fajn, tak zavírám.
